using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CodeMetrics.AI;

public static class SourceFileFilter
{
    private static readonly string[] GeneratedFileSuffixes =
    [
        ".generated.cs",
        ".g.cs",
        ".g.i.cs",
        ".designer.cs",
    ];

    private static readonly string[] BuildOutputDirectoryNames =
    [
        "obj",
        "bin",
    ];

    /// <summary>
    /// The single entry point every probe and the metrics collector use to enumerate source.
    /// Filtering here rather than per probe means no probe can accidentally opt back in to
    /// build output or generated sources.
    /// </summary>
    public static IEnumerable<SyntaxTree> AnalyzableTrees(Compilation compilation, string? solutionRoot)
    {
        return compilation.SyntaxTrees.Where(tree => ShouldAnalyze(tree, solutionRoot));
    }

    public static bool ShouldAnalyze(SyntaxTree tree, string? solutionRoot)
    {
        return ShouldAnalyze(tree.FilePath, solutionRoot) && !HasAutoGeneratedHeader(tree);
    }

    public static bool ShouldAnalyze(string? filePath, string? solutionRoot)
    {
        if (string.IsNullOrWhiteSpace(filePath))
            return true;

        var fullPath = Path.GetFullPath(filePath);

        if (!string.IsNullOrWhiteSpace(solutionRoot))
        {
            var fullRoot = Path.TrimEndingDirectorySeparator(Path.GetFullPath(solutionRoot));

            if (!fullPath.Equals(fullRoot, StringComparison.OrdinalIgnoreCase) &&
                !fullPath.StartsWith(fullRoot + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }
        }

        var normalizedPath = fullPath
            .Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
        var nugetPackageSegment = $"{Path.DirectorySeparatorChar}.nuget{Path.DirectorySeparatorChar}packages{Path.DirectorySeparatorChar}";

        if (normalizedPath.IndexOf(nugetPackageSegment, StringComparison.OrdinalIgnoreCase) >= 0)
            return false;

        return !IsGeneratedPath(normalizedPath);
    }

    /// <summary>
    /// True for build output directories and conventional generated file names. Directory
    /// names are compared as whole path segments so a legitimate folder such as 'Bobbin'
    /// is not mistaken for 'bin'.
    /// </summary>
    private static bool IsGeneratedPath(string normalizedPath)
    {
        var fileName = Path.GetFileName(normalizedPath);
        if (GeneratedFileSuffixes.Any(suffix =>
                fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        var directory = Path.GetDirectoryName(normalizedPath);
        if (string.IsNullOrEmpty(directory))
            return false;

        var segments = directory.Split(
            Path.DirectorySeparatorChar,
            StringSplitOptions.RemoveEmptyEntries);

        return segments.Any(segment =>
            BuildOutputDirectoryNames.Contains(segment, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Detects the canonical Roslyn generated-code marker in the file's leading comments.
    /// This is the most robust of the three signals because it catches generators that
    /// follow none of the file naming or output directory conventions.
    /// Roslyn's own GeneratedCodeUtilities is internal and its public equivalent is only
    /// reachable from a DiagnosticAnalyzer's AnalysisContext, which this tool does not use.
    /// </summary>
    public static bool HasAutoGeneratedHeader(SyntaxTree tree)
    {
        var firstToken = tree.GetRoot().GetFirstToken(includeZeroWidth: true);

        foreach (var trivia in firstToken.LeadingTrivia)
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) &&
                !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            {
                continue;
            }

            var text = trivia.ToString();
            if (text.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
                text.Contains("<autogenerated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
