using CodeMetrics.AI.Metrics;
using CodeMetrics.AI.Tests.Helpers;
using FluentAssertions;

namespace CodeMetrics.AI.Tests.Metrics;

public class MetricsCollectorTests
{
    private static readonly string Root =
        Path.GetFullPath(Path.Combine(Path.GetTempPath(), "CodeMetricsPopulationRoot"));

    private const string Code = """
        class Widget {
            public int Value { get; set; }
            public void Reset() { Value = 0; }
        }
        """;

    private static (List<TypeMetrics> Types, List<MemberMetrics> Members) CollectAt(
        string code, params string[] segments)
    {
        var file = Path.Combine([Root, .. segments]);
        var (_, _, compilation) = RoslynTestHelper.CompileCodeAtPath(code, file);
        return MetricsCollector.Collect("TestProject", compilation, Root);
    }

    [Fact]
    public void Collect_AuthoredSource_CountsTypesAndMembers()
    {
        var (types, members) = CollectAt(Code, "src", "App", "Widget.cs");

        types.Should().ContainSingle().Which.Type.Should().Be("Widget");
        members.Should().NotBeEmpty();
    }

    [Fact]
    public void Collect_GeneratedSource_ExcludedFromPopulation()
    {
        var (types, members) = CollectAt(Code, "obj", "Debug", "net10.0", "Widget.generated.cs");

        types.Should().BeEmpty();
        members.Should().BeEmpty();
    }

    [Fact]
    public void Collect_AutoGeneratedHeader_ExcludedFromPopulation()
    {
        var (types, members) = CollectAt("// <auto-generated/>\n" + Code, "src", "App", "Widget.cs");

        types.Should().BeEmpty();
        members.Should().BeEmpty();
    }
}
