import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';

const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'codemetrics-package-'));
function run(args, cwd, expected = 0) {
  const result = spawnSync(process.execPath, args, { cwd, encoding: 'utf8', timeout: 120_000, windowsHide: true });
  assert.equal(result.status, expected, result.stdout + result.stderr);
  return result.stdout;
}
try {
  const packageRoot = path.resolve(import.meta.dirname, '..');
  const npm = process.env.npm_execpath;
  assert.ok(npm, 'Run through npm run test:package');
  const output = run([npm, 'pack', '--json', '--pack-destination', temporary], packageRoot);
  const packed = JSON.parse(output.slice(output.indexOf('[')))[0];
  const install = path.join(temporary, 'install'); fs.mkdirSync(install);
  run([npm, 'install', '--ignore-scripts', '--omit=dev', '--no-audit', '--no-fund', path.join(temporary, packed.filename)], install);
  const fixture = path.join(temporary, 'fixture'); fs.mkdirSync(fixture);
  fs.writeFileSync(path.join(fixture, 'package.json'), '{"name":"installed-smoke"}');
  fs.writeFileSync(path.join(fixture, 'App.tsx'), "import {useEffect} from 'react'; export function App(){useEffect(async()=>{},[]); return <div/>;}");
  const cli = path.join(install, 'node_modules/codemetrics-ai/dist/cli.js');
  const evidenceCli = path.join(install, 'node_modules/codemetrics-ai/dist/evidence-cli.js');
  assert.ok(fs.readFileSync(cli, 'utf8').startsWith('#!/usr/bin/env node'));
  run([cli, '--scorecard-output', 'before.json', '--sarif', 'before.sarif'], fixture);
  const evidence = JSON.parse(fs.readFileSync(path.join(fixture, 'before.json'), 'utf8'));
  assert.equal(evidence.schemaVersion, 3); assert.ok(evidence.population.members >= 1);
  assert.equal(evidence.analysis.ruleset, 'javascript-typescript-2026-10-09-handler-contracts');
  assert.equal(evidence.dimensions.codeQuality.scoringDecision.operation, 'deductions');
  assert.equal(evidence.dimensions.codeQuality.componentDetails.methodComplexity.score, evidence.dimensions.codeQuality.score);
  assert.equal(evidence.dimensions.codeQuality.componentDetails.decomposition.score, null);
  assert.equal(evidence.dimensions.maintainability.scoring.observations.functionContributions.length, evidence.population.members);
  assert.equal(evidence.dimensions.maintainability.scoring.observations.measurement, 'owned-function-body-v2-type-erasure');
  for (const item of evidence.dimensions.codeQuality.scoring.observations.functionContributions) {
    assert.equal(item.complexityBreakdown.version, 1);
    assert.equal(item.complexityBreakdown.total, item.ownComplexity);
    assert.equal(1 + Object.values(item.complexityBreakdown.counts).reduce((sum, count) => sum + count, 0), item.ownComplexity);
  }
  assert.equal(evidence.dimensions.performanceAsync.findings[0].category, 'asyncEffectCallback');
  run([cli, '--scorecard-output', 'after.json', '--baseline', 'before.json', '--fail-on-new', 'warning', '--comparison-output', 'comparison.json'], fixture);
  run([evidenceCli, '--input', 'after.json', '--baseline', 'before.json', '--max-score-drop', '0', '--sarif', 'after.sarif'], fixture);
  assert.equal(JSON.parse(fs.readFileSync(path.join(fixture, 'comparison.json'), 'utf8')).new.length, 0);
  run([cli, '--project', 'missing.json'], fixture, 2);
  const promises = path.join(temporary, 'promise-fixture'); fs.mkdirSync(promises);
  fs.writeFileSync(path.join(promises, 'package.json'), '{"name":"installed-promises"}');
  fs.writeFileSync(path.join(promises, 'work.ts'), 'export const work = new Promise(async resolve => resolve(1)); export const start = () => [1].forEach(async item => { await Promise.resolve(item); });');
  run([cli, '--scorecard-output', 'before.json'], promises);
  const promiseEvidence = JSON.parse(fs.readFileSync(path.join(promises, 'before.json'), 'utf8'));
  assert.equal(promiseEvidence.dimensions.performanceAsync.score, 0);
  assert.deepEqual(promiseEvidence.dimensions.performanceAsync.findings.map(f => f.category).sort(), ['asyncForEachCallback', 'asyncPromiseExecutor']);
  fs.writeFileSync(path.join(promises, 'work.ts'), 'export const work = new Promise(resolve => resolve(1)); export const start = () => [1].forEach(async item => { await Promise.resolve(item); });');
  run([cli, '--scorecard-output', 'after.json', '--baseline', 'before.json', '--fail-on-new', 'warning', '--max-score-drop', '0', '--sarif', 'after.sarif'], promises);
  const reviewed = JSON.parse(fs.readFileSync(path.join(promises, 'after.json'), 'utf8'));
  assert.equal(reviewed.dimensions.performanceAsync.score, 10);
  assert.equal(reviewed.dimensions.performanceAsync.findings[0].severity, 'info');
  assert.equal(reviewed.dimensions.performanceAsync.scoringDecision.findingEffects[0].effect, 'excluded');
  run([evidenceCli, '--input', 'after.json'], promises);
  const typed = path.join(temporary, 'typed-fixture'); fs.mkdirSync(typed);
  fs.writeFileSync(path.join(typed, 'package.json'), '{"name":"installed-type-erasure"}');
  fs.writeFileSync(path.join(typed, 'code.ts'), 'function plain(value) { const result = transform(value); return result; } function typed(value: string) { const result: string = transform<string>(value!) as string; return result satisfies string; }');
  run([cli, '--scorecard-output', 'evidence.json'], typed);
  const typedEvidence = JSON.parse(fs.readFileSync(path.join(typed, 'evidence.json'), 'utf8'));
  const contributions = typedEvidence.dimensions.maintainability.scoring.observations.functionContributions;
  assert.equal(contributions.length, 2);
  assert.equal(contributions[0].ownHalsteadVolume, contributions[1].ownHalsteadVolume);
  assert.equal(contributions[0].ownMaintainabilityIndex, contributions[1].ownMaintainabilityIndex);
  run([evidenceCli, '--input', 'evidence.json'], typed);
  fs.writeFileSync(path.join(typed, 'code.ts'), `function hotspot(x) { ${'if (x) x--;'.repeat(11)} return x; }`);
  run([cli, '--scorecard-output', 'hotspot.json', '--sarif', 'hotspot.sarif'], typed);
  const hotspot = JSON.parse(fs.readFileSync(path.join(typed, 'hotspot.json'), 'utf8'));
  const finding = hotspot.dimensions.codeQuality.findings[0];
  assert.equal(finding.observations.complexityBreakdown.counts.ifStatements, 11);
  assert.equal(finding.observations.complexityBreakdown.total, finding.observations.measured);
  run([evidenceCli, '--input', 'hotspot.json', '--inspect-output', 'inspection.json'], typed);
  const inspection = JSON.parse(fs.readFileSync(path.join(typed, 'inspection.json'), 'utf8'));
  assert.deepEqual(inspection.evidence.dimensions.codeQuality.findings[0].observations.complexityBreakdown, finding.observations.complexityBreakdown);
  const modules = path.join(temporary, 'module-fixture'); fs.mkdirSync(modules);
  fs.writeFileSync(path.join(modules, 'package.json'), '{"name":"installed-modules"}');
  fs.writeFileSync(path.join(modules, 'a.ts'), "import {b} from './b'; export const a=()=>b;");
  fs.writeFileSync(path.join(modules, 'b.ts'), "export const b=1;");
  run([cli, '--scorecard-output', 'before.json'], modules);
  fs.writeFileSync(path.join(modules, 'b.ts'), "import {a} from './a'; export const b=()=>a;");
  run([cli, '--scorecard-output', 'after.json', '--baseline', 'before.json', '--fail-on-new', 'warning', '--sarif', 'cycles.sarif'], modules);
  const cycleEvidence = JSON.parse(fs.readFileSync(path.join(modules, 'after.json'), 'utf8'));
  assert.equal(cycleEvidence.dimensions.architecture.status, 'skipped');
  assert.equal(cycleEvidence.dimensions.architecture.score, undefined);
  assert.equal(cycleEvidence.dimensions.architecture.dependencyGraph.cycles.length, 1);
  assert.equal(cycleEvidence.dimensions.architecture.findings[0].severity, 'info');
  fs.writeFileSync(path.join(modules, 'index.ts'), "import {a} from './a'; export {a}; export * from './b';");
  run([cli, '--scorecard-output', 'after.json'], modules);
  const splitEvidence = JSON.parse(fs.readFileSync(path.join(modules, 'after.json'), 'utf8'));
  const views = splitEvidence.dimensions.architecture.dependencyGraph.dependencyViews;
  assert.equal(views.version, 2);
  assert.equal(views.implementation.internalValueEdgeCount, 2);
  assert.equal(views.reExports.internalValueEdgeCount, 2);
  assert.equal(views.reExports.highestFanOut[0].id, 'index.ts');
  assert.deepEqual(splitEvidence.dimensions.architecture.dependencyGraph.dependencies.find(edge => edge.from === 'index.ts' && edge.form === 'import').roles, ['reExport']);
  assert.equal(splitEvidence.dimensions.architecture.dependencyGraph.cycles.length, 1);
  run([evidenceCli, '--input', 'after.json', '--inspect-output', 'inspection.json'], modules);
  const graphInspection = JSON.parse(fs.readFileSync(path.join(modules, 'inspection.json'), 'utf8'));
  assert.equal(graphInspection.usable, true);
  assert.deepEqual(graphInspection.evidence.dimensions.architecture.dependencyGraph, splitEvidence.dimensions.architecture.dependencyGraph);
  const handlers = path.join(temporary, 'handler-fixture'); fs.mkdirSync(handlers);
  fs.writeFileSync(path.join(handlers, 'package.json'), '{"name":"installed-handlers"}');
  fs.writeFileSync(path.join(handlers, 'code.ts'), `export async function work(){try {await Promise.resolve(1)} catch { /* Optional operation. */ }}
    const ignore=()=>{}; Promise.reject(1).catch(ignore); Promise.reject(2).then(undefined,ignore);`);
  run([cli, '--scorecard-output', 'evidence.json', '--sarif', 'handlers.sarif'], handlers);
  run([evidenceCli, '--input', 'evidence.json', '--inspect-output', 'inspection.json'], handlers);
  const handlerInspection = JSON.parse(fs.readFileSync(path.join(handlers, 'inspection.json'), 'utf8'));
  const dimensions = handlerInspection.evidence.dimensions;
  assert.equal(handlerInspection.usable, true);
  assert.equal(dimensions.errorHandling.score, 5);
  assert.equal(dimensions.errorHandling.handlerEvidence.totalHandlers, 2);
  assert.equal(dimensions.errorHandling.handlerEvidence.version, 2);
  assert.equal(dimensions.errorHandling.handlerEvidence.referencedCallbackUseSites, 2);
  assert.equal(dimensions.errorHandling.handlerEvidence.documentedEmptyHandlers, 1);
  assert.equal(dimensions.errorHandling.handlerEvidence.unexplainedEmptyHandlers, 1);
  assert.equal(dimensions.errorHandling.findings[0].severity, 'warning');
  assert.equal(dimensions.errorHandling.scoringDecision.findingEffects[0].effect, 'policyInput');
  assert.equal(dimensions.errorHandling.dispositionEvidence.unknownHandlers, 0);
  run([cli, '--scorecard-output', 'rerun.json', '--baseline', 'evidence.json', '--fail-on-new', 'warning', '--max-score-drop', '0'], handlers);
  fs.appendFileSync(path.join(handlers, 'code.ts'), '\nPromise.reject(3).catch(()=>{});');
  run([cli, '--scorecard-output', 'worse.json', '--baseline', 'evidence.json', '--fail-on-new', 'warning', '--max-score-drop', '0'], handlers, 1);
  assert.equal(dimensions.codeQuality.componentDetails.decomposition.population.functions, 2);
  assert.equal(dimensions.codeQuality.componentDetails.decomposition.score, null);
  assert.equal(dimensions.codeQuality.componentDetails.decomposition.version, 2);
  assert.equal(dimensions.codeQuality.componentDetails.decomposition.primaryMeasure, "ownedStatements");
  assert.equal(dimensions.performanceAsync.scoring.observations.eligibleOwners, 2);
  assert.equal(dimensions.performanceAsync.scoring.observations.affectedOwners, 0);
  console.log('Installed package analysis, schema validation, baseline gates, SARIF and invalid-input smoke checks passed.');
} finally { fs.rmSync(temporary, { recursive: true, force: true }); }
