using CodeMetrics.AI.Tests.Helpers;
using FluentAssertions;

namespace CodeMetrics.AI.Tests;

public class ProjectFilterTests
{
    [Fact]
    public void ShouldSkip_TestProject_ReturnsTrue()
    {
        var result = ProjectFilter.ShouldSkip("MyApp.Tests", out var reason);

        result.Should().BeTrue();
        reason.Should().Be("Test project");
    }

    [Fact]
    public void ShouldSkip_AppHost_ReturnsTrue()
    {
        var result = ProjectFilter.ShouldSkip("MyApp.AppHost", out var reason);

        result.Should().BeTrue();
        reason.Should().Be("Aspire orchestration host");
    }

    [Fact]
    public void ShouldSkip_CoreProject_ReturnsFalse()
    {
        var result = ProjectFilter.ShouldSkip("MyApp.Core", out var reason);

        result.Should().BeFalse();
        reason.Should().BeEmpty();
    }

    [Fact]
    public void ShouldSkip_Benchmarks_ReturnsTrue()
    {
        var result = ProjectFilter.ShouldSkip("MyApp.Benchmarks", out var reason);

        result.Should().BeTrue();
        reason.Should().Be("Benchmark project");
    }

    [Fact]
    public void SourceFileFilter_InSolutionRoot_ReturnsTrue()
    {
        var root = Path.GetFullPath(Path.Combine(Path.GetTempPath(), "CodeMetricsSourceRoot"));
        var file = Path.Combine(root, "src", "App", "Service.cs");

        SourceFileFilter.ShouldAnalyze(file, root).Should().BeTrue();
    }

    [Fact]
    public void SourceFileFilter_OutsideSolutionRoot_ReturnsFalse()
    {
        var root = Path.GetFullPath(Path.Combine(Path.GetTempPath(), "CodeMetricsSourceRoot"));
        var file = Path.GetFullPath(Path.Combine(Path.GetTempPath(), "OtherRoot", "Service.cs"));

        SourceFileFilter.ShouldAnalyze(file, root).Should().BeFalse();
    }

    [Fact]
    public void SourceFileFilter_NuGetPackagePath_ReturnsFalse()
    {
        var root = Path.GetFullPath(Path.Combine(Path.GetTempPath(), "CodeMetricsSourceRoot"));
        var file = Path.Combine(root, ".nuget", "packages", "some.package", "contentFiles", "Service.cs");

        SourceFileFilter.ShouldAnalyze(file, root).Should().BeFalse();
    }

    // ── Generated source exclusion ────────────────────────────────────────────

    private static readonly string GeneratedTestRoot =
        Path.GetFullPath(Path.Combine(Path.GetTempPath(), "CodeMetricsSourceRoot"));

    [Theory]
    [InlineData("obj", "Debug", "net10.0", "OpenApiXmlCommentSupport.generated.cs")]
    [InlineData("obj", "Debug", "Service.cs")]
    [InlineData("bin", "Debug", "Service.cs")]
    [InlineData("src", "App", "Model.generated.cs")]
    [InlineData("src", "App", "Model.g.cs")]
    [InlineData("src", "App", "Model.g.i.cs")]
    [InlineData("src", "App", "Form.designer.cs")]
    [InlineData("src", "App", "FORM.Designer.CS")]
    public void SourceFileFilter_GeneratedSource_ReturnsFalse(params string[] segments)
    {
        var file = Path.Combine([GeneratedTestRoot, .. segments]);

        SourceFileFilter.ShouldAnalyze(file, GeneratedTestRoot).Should().BeFalse();
    }

    [Theory]
    [InlineData("Bobbin", "Service.cs")]
    [InlineData("Objects", "Service.cs")]
    [InlineData("src", "App", "Generated.cs")]
    [InlineData("src", "App", "Designer.cs")]
    [InlineData("src", "App", "Service.cs")]
    public void SourceFileFilter_AuthoredSource_ReturnsTrue(params string[] segments)
    {
        var file = Path.Combine([GeneratedTestRoot, .. segments]);

        SourceFileFilter.ShouldAnalyze(file, GeneratedTestRoot).Should().BeTrue();
    }

    [Fact]
    public void SourceFileFilter_AutoGeneratedHeader_ReturnsFalse()
    {
        const string code = """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            // </auto-generated>
            //------------------------------------------------------------------------------
            class C { }
            """;

        var tree = RoslynTestHelper.ParseCode(code);

        SourceFileFilter.HasAutoGeneratedHeader(tree).Should().BeTrue();
        SourceFileFilter.ShouldAnalyze(tree, solutionRoot: null).Should().BeFalse();
    }

    [Fact]
    public void SourceFileFilter_AutogeneratedHeaderVariant_ReturnsFalse()
    {
        const string code = """
            // <autogenerated />
            class C { }
            """;

        var tree = RoslynTestHelper.ParseCode(code);

        SourceFileFilter.HasAutoGeneratedHeader(tree).Should().BeTrue();
    }

    [Fact]
    public void SourceFileFilter_AuthoredFileWithLeadingComment_ReturnsTrue()
    {
        const string code = """
            // Copyright notice, hand written.
            class C { }
            """;

        var tree = RoslynTestHelper.ParseCode(code);

        SourceFileFilter.HasAutoGeneratedHeader(tree).Should().BeFalse();
        SourceFileFilter.ShouldAnalyze(tree, solutionRoot: null).Should().BeTrue();
    }
}
